### PR TITLE
restore shield

### PR DESCRIPTION
**Pull request by Adnan1091**
Ingame setting has a option to disable shield.So even new pistols isn't compatible with shield it doesn't mean you need to remove it.

### CODE REVIEW

**Comment by Adnan1091** [comment]
Please dude,there aren't any new updates for this application.So let us just restore old content.

**Comment by HowToDoThis** [comment]
I don't think this is a valid requesting, since there is already have a switch with ENABLE_SHIELD to build cs1.6 shield, just adding define while building.

**Comment by Adnan1091** [comment]
How can i enable it?Or i can modify my pull request to make it pass build test.

**Comment by HowToDoThis** [comment]
Just adding Define ENABLE_SHEILD which I said earlier to enable using shield, MoeMod didn't remove code, just hide on master build

**Comment by Adnan1091** [comment]
Do i edit it on the code.Or it is a setting on appveyor?

**Comment by HowToDoThis** [comment]
Just adding something arguments like -DENABLE_SHEILD to compiler/linker, just search CMake how to add define and there is a lots of results to teaching u how to add define to CMAKE or something and do this on locally, master would not pushing this pull request.

**Comment by Adnan1091** [comment]
Which file do i add add_definitions(-DENABLE_SHIELD) to prevent a bad pull request?I looked at the files but couldn't find build.conf

**Comment by Adnan1091** [comment]
Closing this as there is an another way to renable shield.

**Pull request closed without merging**
